In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('data/train.csv')
df

,customer_id,age,location,subscription_type,payment_plan,num_subscription_pauses,payment_method,customer_service_inquiries,signup_date,weekly_hours,average_session_length,song_skip_rate,weekly_songs_played,weekly_unique_songs,num_favorite_artists,num_platform_friends,num_playlists_created,num_shared_playlists,notifications_clicked,churned
0,1,32,Montana,Free,Yearly,2,Paypal,Medium,-1606,22.391362,105.394516,0.176873,169,109,18,32,52,35,46,0
1,2,64,New Jersey,Free,Monthly,3,Paypal,Low,-2897,29.294210,52.501115,0.981811,55,163,44,33,12,25,37,1
2,3,51,Washington,Premium,Yearly,2,Credit Card,High,-348,15.400312,24.703696,0.048411,244,117,20,129,50,28,38,0
3,4,63,California,Family,Yearly,4,Apple Pay,Medium,-2894,22.842084,83.595480,0.035691,442,252,47,120,55,17,24,0
4,5,54,Washington,Family,Monthly,3,Paypal,High,-92,23.151163,52.578266,0.039738,243,230,41,66,40,32,47,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124996,32,California,Student,Monthly,4,Debit Card,Low,-1895,29.161399,7.176704,0.893839,460,22,18,199,71,41,41,0
124996,124997,56,Maine,Premium,Yearly,2,Debit Card,Low,-2778,44.744198,105.069363,0.668759,315,16,48,185,67,23,30,0
124997,124998,45,Maine,Family,Monthly,0,Paypal,Medium,-604,15.200073,78.064000,0.286604,11,206,48,40,78,40,28,0
124998,124999,69,Maine,Free,Monthly,4,Paypal,High,-2570,35.270053,20.921062,0.092528,451,108,15,41,3,35,9,1
124999,125000,18,Vermont,Family,Monthly,4,Apple Pay,Low,-1934,9.263155,11.495242,0.067277,19,79,9,54,77,27,2,0

## RFM 기반 데이터 가공
- 이 데이터는 거래 데이터가 아니라 행동 데이터라서 클래식 RFM(구매 기반)이 아니라 Engagement-based RFM으로 만들고, Engagement 컬럼을 추가하였다.

|컬럼명|사용 컬럼|의미|
|---|---|---|
|Recency|notifications_clicked|최근 활동 정도를 나타냄. 값이 클수록 활동이 활발함.|
|Frequency|weekly_songs_played|사용 빈도. 최근 일주일 간 들은 노래 곡 수.|
|Monetary|weekly_hours|일주일 간 평균 사용 시간. 금액 대신 사용 가치로 대체.|
|Engagement|num_playlists_created + num_platform_friends + num_shared_friends|플랫폼에서 얼마나 활발하게 활동했는지 지표.|

In [6]:
retail_df = pd.DataFrame()
retail_df['Recency'] = df['notifications_clicked']
retail_df['Frequency'] = df['weekly_songs_played']
retail_df['Monetary'] = df['weekly_hours']
retail_df['Engagement'] = df[['num_playlists_created', 'num_platform_friends', 'num_shared_playlists']].sum(axis=1)
retail_df

        Recency  Frequency   Monetary  Engagement
0            46        169  22.391362         119
1            37         55  29.294210          70
2            38        244  15.400312         207
3            24        442  22.842084         192
4            47        243  23.151163         138
...         ...        ...        ...         ...
124995       41        460  29.161399         311
124996       30        315  44.744198         275
124997       28         11  15.200073         158
124998        9        451  35.270053          79
124999        2         19   9.263155         158

[125000 rows x 4 columns]